### ISSUE TITLE
Crashes with Python 3.6 - MacOS Sierra

### ISSUE THREAD

**Issue by achampion** [ludwigschwardt/python-gnureadline#50] opened 2016-12-31 05:29 UTC
Installing on Python 3.6 causes the REPL to Abort on input:

    Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import gnureadline
    >>> <return>
    Python(30507,0x7fffba27b3c0) malloc: *** error for object 0x100522640: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

`easy_install-3.6 gnureadline` says:

    Best match: gnureadline 6.3.3

And has a number of linker warnings:

    ld: warning: object file (readline/libreadline.a(history.o)) was built for newer OSX version (10.12) than being linked (10.6)
    ld: warning: object file (readline/libreadline.a(keymaps.o)) was built for newer OSX version (10.12) than being linked (10.6)
    ...

CLang

    $ clang --version
    Apple LLVM version 8.0.0 (clang-800.0.42.1)

**Comment by fwkz** [comment] 2017-01-28 11:11
Same here (**macOS** Sierra 10.12.3) `gnureadline` crash entire python process... @ludwigschwardt Is there any way how I can help you fixing this?

**Comment by scopatz** [comment] 2017-02-26 16:58
We are still seeing this with xonsh, xonsh/xonsh#2078

**Comment by ludwigschwardt** [comment] 2017-02-28 09:04
Sorry for the wait... You've given me a reason to upgrade to Sierra (still on El Capitan here).

**Comment by scopatz** [comment] 2017-02-28 18:50
Thanks @ludwigschwardt, I think a fix would be very much appreciated!

**Comment by ludwigschwardt** [comment] 2017-02-28 20:33
I can recreate this on El Capitan, so hopefully that means a quicker fix :-)

**Comment by ludwigschwardt** [comment] 2017-03-02 13:05
I've just realised that I forgot to release 6.3.8 back in October 2015... Talk about getting distracted! I suspect the birth of my son in August 2015 had something to do with it :-)

Anyhow, it seems that the latest master branch in the repository does not have this issue. Please check if that is the case for you too.

**Comment by mitnk** [comment] 2017-03-03 09:52
Congrats on that event!!

>  it seems that the latest master branch in the repository does not have this issue.

I can confirm this - master is good. Just FYI, Install it from master, the gnureadline version still show 6.3.3.

**Comment by mitnk** [comment] 2017-03-27 16:26
@ludwigschwardt Any plan to release a new version to PYPI?

**Comment by ludwigschwardt** [comment] 2017-03-27 21:44
Yes - I want to use the MacPython wheel generation mechanism to simplify my life this time around, so that's the current hold-up.

**Comment by ivanov** [comment] 2017-05-17 07:20
I think I was just bitten by this as well in ipython/rlipython#16

**Comment by braham-snyder** [comment] 2017-05-21 05:15
here's the command for the workaround mentioned above (again, note that this version also shows 6.3.3 despite this version working and PyPI's not):
```
pip install https://github.com/ludwigschwardt/python-gnureadline/archive/master.zip --upgrade
```

**Comment by trailblazr** [comment] 2017-05-26 15:58
the normal  `$ python` on the commandline did not work for me. I always got the following:

```
> python
Python 3.6.1 (default, Apr 24 2017, 06:18:27) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
python(54039,0x7fffb769e3c0) malloc: *** error for object 0x10600d0d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```


 I solved this on macOS Sierra by doing the following in my virtualenv-environment:
`$ pip install ipython`
`$ ipython`
this gave me a working interactive python shell back and looked like this:

```
> ipython
Python 3.6.1 (default, Apr 24 2017, 06:18:27) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os

In [2]: 
```

 **None** of the things mentioned in this thread really worked for me, sorry.

**Comment by ivanov** [comment] 2017-05-30 23:50
`pip install https://github.com/ludwigschwardt/python-gnureadline/archive/master.zip --upgrade` also worked for me on Python.org 3.6.1 release.

**Comment by bcb** [comment] 2017-08-16 05:07
Master branch works for me. I would like a PyPi release.

**Comment by rbahumi** [comment] 2017-10-05 01:06
Just ran `pip install --upgrade ipython` and the issue was solved.

**Comment by ilovezfs** [comment] 2017-10-17 05:26
@ludwigschwardt a gentle ping on this. Are there remaining blockers for a new PyPI release?

**Comment by ludwigschwardt** [comment] 2017-10-20 10:08
Thanks @ilovezfs, your gentle ping finally did the trick :-)

I've released 6.3.8 with MacPython wheels - please check that this works for you and apologies again for the long (2-year) delay...

**Comment by rish321** [comment] 2017-12-23 07:13
Successfully installed gnureadline-6.3.8

Still this error showing up

**Comment by BeautifulTommorow** [comment] 2018-04-13 05:29
thanks

**Comment by ludwigschwardt** [comment] 2019-07-11 10:12
I learnt some good lessons from this issue... The latest gnureadline 8.0.0 release already supports Python 3.8 😄

I'm closing this because the issue seems to be resolved (and the new release was tested on Mojave too). Please feel free to re-open if necessary.

**Closed by ludwigschwardt** 2019-07-11 10:12 UTC
