### ISSUE TITLE
Installation Fails on Python 3.5.0 (OS X 10.9.5)

### ISSUE THREAD

**Issue by jackmaney** [ludwigschwardt/python-gnureadline#45] opened 2015-09-18 15:51 UTC
I attempted to do a `pip install ipython` on a fresh installation of 3.5.0, but the installation fails on `gnureadline`. The log output of `pip install gnureadline` can be found at:

https://gist.github.com/jackmaney/c93e38816063f54d2cc3

Note that `pip install gnureadline` works just fine in 3.4.3 (or any other version of Python).

**Comment by RazerM** [comment] 2015-09-20 14:19
When the pip installation failed, I was able to install this with Python 3.5 (OS X 10.10.5) by cloning the repository and running `python setup.py install`.

**Comment by ludwigschwardt** [comment] 2015-09-21 14:26
Thanks to @matthew-brett I am moving gnureadline wheel generation over to @MacPython, which will keep up to date with the latest Python. You can find a binary wheel for Python 3.5.0 and OS X 10.9.5 [here](http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/gnureadline-6.3.3-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl) so long. The plan is to tidy up the package, make a 6.3.8 release and have wheels for all decent Pythons and OS Xes soon.

**Comment by jackmaney** [comment] 2015-09-22 16:27
Thank you. I take it 6.3.8 will be up on PyPI, as well?

**Comment by ludwigschwardt** [comment] 2015-09-22 19:26
Yes, that's the plan. Now to find a gap :-)

**Comment by MagisDing** [comment] 2015-09-24 07:30
I met the same problem with @jackmaney.  
@ludwigschwardt Please forgive my ignorance.  I am still little confused, how to use the @Macpython to keep all the python packages up to date? Could it be conflict with pip?

**Comment by ludwigschwardt** [comment] 2015-09-24 17:48
No problem Yuzhe,

The MacPython project on GitHub is a set of tools to build binary distributions for popular Python packages containing C extensions (known as *wheels*). If there is a wheel for your specific version of Python and operating system, it simplifies installation a lot as you don't need to compile anything.

The problem is that I haven't made a wheel for Python 3.5 yet, which is why your system is trying to compile gnureadline from source. While this *should* also work, you probably have a strange compiler and/or Python setup which caused installation to fail.

Instead of debugging your compilation, it is much easier to just provide a wheel. The plan is to put the wheel for Python 3.5 on PyPI, which will let pip find it automatically and everything will just work, like for the previous versions of Python. I will combine this with a new 6.3.8 release, which is why the wheel is not there yet.

If you want to try it out, download the Python 3.5 wheel from [here](http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/gnureadline-6.3.3-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl) and install it with *pip install <long_filename>.whl*.

Hope that helps!

**Comment by MagisDing** [comment] 2015-09-25 12:37
@ludwigschwardt  Thanks for your guide and detailed explanation! This problem has haunted me for a while(since python 3.5 came out), now finally I got ipython installed successfully. 

Talking about MacPython, so in the future what I need is to download the wheel for each specific package, then make pip installation?

**Comment by ludwigschwardt** [comment] 2015-09-25 16:48
Once I have the wheels on PyPI, it should not be necessary - the normal pip install will work.

**Comment by ludwigschwardt** [comment] 2015-09-26 00:06
Hi @jackmaney, just to check - were you compiling gnureadline with GNU gcc or the usual Apple clang? What is the output of `cc -v` on your system?

**Comment by matthew-brett** [comment] 2015-09-26 00:08
I hate to bring it up again - but is there any downside to uploading the built 3.5.0 wheel to pypi in the meantime?

**Comment by matthew-brett** [comment] 2015-09-26 00:09
It might even help smoke out any problems in the install...

**Comment by ludwigschwardt** [comment] 2015-09-26 00:15
Good point - no downside, just me dithering :-)

**Comment by ludwigschwardt** [comment] 2017-10-20 10:20
I've finally pushed 6.3.8 out the door and onto PyPI. Apologies again for the 2-year delay... I'm closing this for now - feel free to re-open if the issue persists.

**Closed by ludwigschwardt** 2017-10-20 10:20 UTC
