### ISSUE TITLE
VI editing mode - delete/change over motion broken 

### ISSUE THREAD

**Issue by mario-grgic** [ludwigschwardt/python-gnureadline#12] opened 2011-12-24 02:42 UTC
I'm on Mac OS X 10.6.8 using pre-installed python 2.6.1 and I have installed readline-6.1.0-py2.6-macosx-10.6-universal.egg. My .input.rc looks like this:
```
set completion-ignore-case On
# TAB: menu-complete

Tab: complete
set editing-mode vi
```
When I start interactive python most of VI editing functionality works, however delete operator in conjunction with motion does not work. For example if the line is 
``` Python
print "Hello There"
```
and the cursor is on the first letter p and you are in normal mode (ESC) typing f" correctly moves you to the first quote. Hitting l moves correctly one space left. Hitting df" should delete until the next quote i.e. erase text Hello There so the line becomes 
``` Python
print "" 
```
But instead you get a beep and the cursor is moved forward just before the last quote and nothing is deleted. This is clearly wrong. 

Similarly c (change) operator doesn't work over motion either, even though motion commands alone work properly. 

Note that readline library does support delete and change operators over motion.

**Comment by ludwigschwardt** [comment] 2015-09-26 00:51
This still seems to be an issue on the latest gnureadline (unreleased 6.3.8), on both Python 2.7.10 and Python 3.5.0 on OS X 10.9.5, at least on my system.

I'm guessing the problem lies somewhere in the Python module itself, but I'm not enough of an expert to debug this. I would appreciate any more feedback on this.

**Comment by ludwigschwardt** [comment] 2019-06-20 12:57
Hi @mario-grgic @andreas-schmidt and others,

I revisited this ancient issue after updating to readline 8.0 in the latest master of this package. I was curious whether the vi commands now work. Compiling on an old Mac OS X 10.6.8 machine (Mario's original setup!) I can confirm the following:

Python 2.7.15 + gnureadline 6.3.8 = does NOT work
Python 3.7.0 + gnureadline 6.3.8 = works

Python 2.7.15 + gnureadline 8.0.0 = works :-)
Python 3.7.0 + gnureadline 8.0.0 = works

So there is hope...

Also, for the record, the vi commands necessary to go from
``` Python
print "Hello There"
```
to
``` Python
print "" 
```
are
```
<ESC>
f"
l
dt"
```
(i.e. the last command is not `df"` as in the original report).

**Comment by ludwigschwardt** [comment] 2019-07-11 09:40
This seems to be fixed, so I'm closing the issue. Feel free to re-open if it's not the case.

**Closed by ludwigschwardt** 2019-07-11 09:40 UTC
